import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-finish-goods',
  templateUrl: './finish-goods.component.html',
  styleUrls: ['./finish-goods.component.scss']
})
export class FinishGoodsComponent {
  showSpinner:boolean = true;

  ngOnInit(){
    setTimeout(() => {
      this.showSpinner = false
    }, 1000);
  }

  viewFinishGoodsData: any = [
    {
      unique_id:"123",
      brand:"Ciana",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana2",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana3",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana4",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
    {
      unique_id:"123",
      brand:"Ciana5",
      product:"T-shirt",
      design:"C-1002",
      avl_qty:1500
    },
];
}
